name: Tag
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  tag:
    name: Add tag to source repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: alist-dev/desktop
          token: ${{ secrets.MY_TOKEN }}

      - name: Add tag
        run: |
          git config --local user.email "i@nn.ci"
          git config --local user.name "Andy Hsu"
          git tag -a ${{ github.ref_name }} -m "${{ github.ref_name }}"

      - name: Push tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          repository: alist-dev/desktop